#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    spinnerServo,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    goalCapture,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MUX1 		 msensor_S4_1 //Definitions for mux sensors
#define touch 	 msensor_S4_2
#define sonar    msensor_S4_3

#include "IRsensor.c" //IR functions
#include "fourWheelMovement.c" //Big robot movement functions
#include "liftFunctions.c" //Lift and spinner functions
#include "gyroSensor.c" //gyro functions
#include "MovementCommon.c" //Math or calculation functions
#include "sonarSensor.c" //Sonar functions
#include "autoProgramQuestions.c" //Question functions

void strategyA()
{
	gyroTurn(30, 90, dLeft);
	travelDistance(45, dBackward);
	strafeDist(15, 30, dLeft);
	wait1Msec(3000); //lift scores in center goal ADD LIFT FUNCTION
	gyroTurn(30, 10, dLeft);
	strafeDist(45, 30, dLeft);
	travelDistance(125, dBackward);
}

void strategyB()
{
	strafeDist(15, 30, dRight);
	travelDistance(15, dBackward);
	wait1Msec(3000);
	gyroTurn(30, 10, dLeft);
	strafeDist(45, 30, dLeft);
	travelDistance(125, dBackward);
}

void strategyC()
{
	strafeDist(50, 30, dRight);
	gyroTurn(30, 60, dRight);
	strafeDist(40, 30, dRight);
	wait1Msec(3000);
	gyroTurn(30, 10, dLeft);
	strafeDist(45, 30, dLeft);
	travelDistance(125, dBackward);
}

task main()
{
	disableDiagnosticsDisplay();
	int irValue = getIRReading();
	strafeDist(40, 30, dRight);
	displayCenteredTextLine(1, "IR = %i", irValue);
	if (irValue == 2)
	{
		strategyA();
	}
	else
	{
		irValue = getIRReading();
		if (irValue == 2)
		{
			strategyA();
		}
		else if (irValue == 3)
		{
			displayCenteredTextLine(6, "C1");
			wait1Msec(20000);
			//strategyC1();
		}
		else
		{
			gyroTurn(10, 5, dRight);
			int irValue1 = getIRReading();
			gyroTurn(10, 10, dLeft);
			int irValue2 = getIRReading();
			eraseDisplay();
			displayCenteredTextLine(2, "IR1 = %i", irValue1);
			displayCenteredTextLine(3, "IR2 = %i", irValue2);
			if (irValue1 == 2 || irValue2 == 2)
			{
				gyroTurn(10, 5, dRight);
				strategyA();
			}
			else
			{
				strafeDist(20, 30, dRight);
				gyroTurn(30, 35, dLeft);
				resetEncoders();
				while (irValue != 4)
				{
					irValue = getIRReading();
					strafe(20);
					int enc = abs(nMotorEncoder[rightFront]);
					displayCenteredTextLine(3, "distance=%i", enc);
					wait1Msec(1);
				}
				stopMotors();
				int enc = abs(nMotorEncoder[rightFront]);
				displayCenteredTextLine(1, "enc = %i", enc);
				wait1Msec(20000);
				if (enc < 1800)
				{
					strategyB();
				}
				else
				{
					strategyC();
				}
			}
		}
	}
}
