#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutoProgramQuestions.c"
#include "fourWheelMovement.c"
#include "autoKickstand.c"
#include "autoRamp.c"
#include "autoIR.c"
#include "autoTube.c"

task main()
{
	setBluetoothOff();

	bool check = false;
	int timeDelay;
	bool RPGKickStand;
	bool RPGStart;


	do
	{
		timeDelay = questionInt("Amount of delay", "left = -1 sec","right = +1 sec", 0 , 30);//asks the questions and sets RPGtime as the answer either true or false
		waitTillNoButton();
		eraseDisplay();

		RPGStart = questionBool("r u starting:","left = floor","right = ramp");
		waitTillNoButton();
		eraseDisplay();

		RPGKickStand = questionBool("do kickstand?","left = no","right = yes");
		waitTillNoButton();
		eraseDisplay();

		RPGtubeDump = questionInt("which tube?", "left = lower hight(1 lowest)", "right = higher hight(4 highest)", 1, 4);
		waitTillNoButton();
		eraseDisplay();

		string test1;// = "delay = " + timeDelay;
		string test2;// = RPGStart;
		string test3;// = "kickstand = " + RPGKickStand;
		string tubeDump;// = "tubeDump = " + RPGtubeDump

		sprintf(test1, "delay = %i", timeDelay);
		sprintf(test2, "location = %i", RPGStart);
		sprintf(test3, "Kickstand = %i", RPGKickStand);
		sprintf(tubeDump, "tumb to dump = %i", RPGKickStand);

		displayCenteredTextLine(1, "your values are:");
		displayCenteredTextLine(4, tubeDump);
		displayCenteredTextLine(5,  test1);
		displayCenteredTextLine(6,  test2);
		displayCenteredTextLine(7, test3);

		check = questionBool("is this right","left = no","right = yes");
		waitTillNoButton();
	}
	while (false == check);

	waitForStartOrButton();


	wait1Msec(timeDelay*1000)

	if(RPGStart == true)//starting on ramp
	{
		rampOff();
	}

	else if(RPGStart == False)// starting on Floor
	{
		if(RPGKickstand == True)
		{
			autoKickstand();
		}

		else
		{
			//move into location
		}
	}

	else
	{
	}

	if(RPGtubeDump == 1)
	{
		autoTubes();
	}

	else if(RPGtubeDump == 2)
	{
		autoTubes();
	}

	else if(RPGtubeDump == 3)
	{
		autoTubes();
	}

	else if(RPGtubeDump == 4)
	{
		autoTubes();
	}

	else
	{}

}
