#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     rightBack,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//all the distance numbers are bogus

#include "functions\fourWheelMovement.c"
int tubeDist;

void goToTube()
{
	int travelDist;
	while(travelDist < tubeDist)
	{
		forward(50);
	}
	while(travelDist >= tubeDist)
	{
		stopMotors();
	}
}

void tossBall()
{
	//toss dat ball like an awesome boss
}

task main()
{	goToTube();
	tossBall();
	stopMotors();
}
