#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "programs\functions\twoWheelMovement.c"
#include "drivers\hitechnic-sensormux.h"     //Drivers for IR Beacon
#include "drivers\hitechnic-irseeker-v2.h"

int getIRReading(tSensors ir_seeker)
{
  wait1Msec(1);                              // Wait 1 ms
  int ir = HTIRS2readACDir(ir_seeker);      // IR receiver -> ir variable
  wait1Msec(1);                              // Down time before recheck
  return ir;
}

void faceIR(tSensors ir_seeker)
{
	int	ir_value = getIRReading(ir_seeker);
	do
	{
		if(ir_value < 2)
		{
			leftTurn(50);
		}
		else if(ir_value > 2)
		{
			rightTurn(50);
		}
		wait1Msec(1);
		ir_value = getIRReading(ir_seeker);
	}
	while(ir_value != 2);
}

task main()
{
	faceIR(IR);
	stopMotors();
}
