#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     smux,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_6,    goalCapture,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutoProgramQuestions.c"
#include "fourWheelMovement.c"
#include "autoKickstand.c"
#include "autoRamp.c"
#include "autoIR.c"
#include "autoTubes.c"

task main()
{
	setBluetoothOff();

	bool check = false;
	int timeDelay;
	bool RPGKickStand;
	bool RPGStart;
	int RPGtubeDump;


	do
	{
		timeDelay = questionInt("Amount of delay", "left = -1 sec","right = +1 sec", 0 , 30);//asks the questions and sets RPGtime as the answer either true or false
		waitTillNoButton();
		eraseDisplay();

		RPGStart = questionBool("r u starting:","left = floor","right = ramp");
		waitTillNoButton();
		eraseDisplay();

		RPGKickStand = questionBool("do kickstand?","left = no","right = yes");
		waitTillNoButton();
		eraseDisplay();

		RPGtubeDump = questionInt("which tube?", "left = lower hight(1 lowest)", "right = higher hight(4 highest)", 1, 4);
		waitTillNoButton();
		eraseDisplay();

		string test1;// = "delay = " + timeDelay;
		string test2;// = RPGStart;
		string test3;// = "kickstand = " + RPGKickStand;
		string tubeDump;// = "tubeDump = " + RPGtubeDump

		sprintf(test1, "delay = %i", timeDelay);
		sprintf(test2, "location = %i", RPGStart);
		sprintf(test3, "Kickstand = %i", RPGKickStand);
		sprintf(tubeDump, "tumb to dump = %i", RPGKickStand);

		displayCenteredTextLine(1, "your values are:");
		displayCenteredTextLine(4, tubeDump);
		displayCenteredTextLine(5,  test1);
		displayCenteredTextLine(6,  test2);
		displayCenteredTextLine(7, test3);

		check = questionBool("is this right","left = no","right = yes");
		waitTillNoButton();
	}
	while (false == check);

	waitForStartOrButton();


	wait1Msec(timeDelay*1000);

	if(RPGStart == true)//starting on ramp
	{
		rampOff();
	}

	else if(RPGStart == false)// starting on Floor
	{
		if(RPGKickStand == true)
		{
			autoKickstand();
		}

		else
		{
			//move into location
		}
	}

	else
	{
	}

	if(RPGtubeDump == 1)
	{
		autoTubes();
	}

	else if(RPGtubeDump == 2)
	{
		autoTubes();
	}

	else if(RPGtubeDump == 3)
	{
		autoTubes();
	}

	else if(RPGtubeDump == 4)
	{
		autoTubes();
	}

	else
	{}

}
