#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     smux,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_6,    goalCapture,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "fourWheelMovement.c";
#include "MovementCommon.c";
#include "gyroSensor.c";

typedef enum {eshort, emid, etall} eTube;

void captureTube()
{
      int iCRate = servoChangeRate[goalCapture];	// Save change rate
			servoChangeRate[goalCapture] = 0; 					// Max Speed
			servo[goalCapture] = 66;					// Set servo position
			wait1Msec(20);
			servoChangeRate[goalCapture] = iCRate;			// Reset the servo
}

void releaseTube()
{
			int iCRate = servoChangeRate[goalCapture];	// Save change rate
			servoChangeRate[goalCapture] = 0; 					// Max Speed
			servo[goalCapture] = 66;					// Set servo position
			wait1Msec(20);
			servoChangeRate[goalCapture] = iCRate;			// Reset the servo
}

void placeTube(int possision)
{
		if(possision == 1)
		{
			gyroTurn(70,50,dRight);
			travelDistance(1);
			captureTube();
		}

		else if(possision == 2)
		{
			gyroTurn(70, 50, dRight);
			travelDistance(2);
			captureTube();
		}

		else if(possision == 3)
		{
			gyroTurn(70, 45, dRight);
			travelDistance(1);
			captureTube();
		}

		else
		{

		}
releaseTube();
}

void chooseTube(eTube Tube)
{
		if(tube == eshort)
		{
			gyroTurn(50, 0, dRight);
			travelDistance(1);
			captureTube();
		}
		else if(tube == emid)
		{
			gyroTurn(50, 90, dRight);
			travelDistance(1);
			captureTube();
		}

		else if(tube == etall)
		{
			gyroTurn(50, 45, dRight);
			travelDistance(1);
			captureTube();
		}

		else
		{
		}
}

void getTube(eTube tube, int kickstandP)
{
	if(kickstandP == 1)
	{
		strafe();
		wait1Msec();
		travelDistance();
		rightTurn();
		gyroTurn(90);
		travelDistance(-);
		chooseTube(tube);

	}
	else if(kickstandP == 2)
	{
		chooseTube(tube)
	}

	else if(kickstandP == 3)
	{
		chooseTube(tube)
	}

	else
	{

	}
}

void autoTubes();
{
	getTube();
	PlaceTube();
}

task main()
{
	autoTubes();
}
