#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     rightCollecter, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftCollecter, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    goalCapture,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "fourWheelMovement.c";
#include "MovementCommon.c";
#include "gyroSensor.c";

typedef enum {dshort, dmid, dtall} eTube

void captureTube()
{
      int iCRate = servoChangeRate[goalCapture];	// Save change rate
			servoChangeRate[goalCapture] = 0; 					// Max Speed
			servo[goalCapture] = 66;					// Set servo position
			wait1Msec(20);
			servoChangeRate[goalCapture] = iCRate;			// Reset the servo
}

void releaseTube()
{
			int iCRate = servoChangeRate[goalCapture];	// Save change rate
			servoChangeRate[goalCapture] = 0; 					// Max Speed
			servo[goalCapture] = 66;					// Set servo position
			wait1Msec(20);
			servoChangeRate[goalCapture] = iCRate;			// Reset the servo
}

void placeTube(int possision)
{
		if(possision == 1)
		{
			rightTurn(50);
			gyroTurn(0)
			travelDistance();
			captureTube();
		}

		else if(possision == 2)
		{
			rightTurn(50);
			gyroTurn(90)
			travelDistance();
			captureTube();
		}

		else if(possision == 3)
		{
			rightTurn(50);
			gyroTurn(45)
			travelDistance();
			captureTube();
		}

		else
		{

		}
releaseTube();
}

void chooseTube(eTube Tube)
{
		if(tube == eshort)
		{
			rightTurn(50);
			gyroTurn(0)
			travelDistance();
			captureTube();
		}
		else if(tube == emid)
		{
			rightTurn(50);
			gyroTurn(90)
			travelDistance();
			captureTube();
		}

		else if(tube == etall)
		{
			rightTurn(50);
			gyroTurn(45)
			travelDistance();
			captureTube();
		}

		else
		{
		}
}

void getTube(eTube tube)
{
	if(/*kickstand possistion == 1*/)
	{
		strafe();
		wait1Msec();
		travelDistance();
		rightTurn();
		gyroTurn(90);
		travelDistance(-);
		chooseTube(tube);

	}
	else if(/*kickstand possistion == 2*/)
	{
		chooseTube(tube)
	}

	else if(/*kickstand possistion == 3*/)
	{
		chooseTube(tube)
	}

	else
	{

	}
}

task main()
{
	getTube();
	PlaceTube();
}
