#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// this is code for testing anything
#include "rpgCommon.c"
#include "IRsensor.c"

task main()
{
	eraseDisplay();
	int ir;
	while(true)
	{
		ir = getIRReading(IR);
		string text = sprintf(text, "ir=%i", ir);
		displayCenteredTextLine(1, text);
	}
}
