#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    goalCapture,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rpgCommon.c"
#include "IRsensor.c"
#include "fourWheelMovement.c"
#include "hitechnic-sensormux.h"     //Drivers for IR Beacon
#include "gyroSensor.c"
#include "gyroMovement.c"
#include "MovementCommon.c"
//#include "turnFunction.c"

float findIR(tSensors ir_seeker)
{
	resetEncoders();
	int	ir_value = getIRReading(ir_seeker);
	backward(50);
	wait1Msec(100);
	repeatUntil((ir_value == 2)||(abs(nMotorEncoder(leftFront))> 10000))
	{
		wait1Msec(1);
		ir_value = getIRReading(ir_seeker);
	}
	stopMotors();
	string text;
		int encoderValue = (abs(nMotorEncoder[leftFront]) + abs(nMotorEncoder[rightFront])) / 2;
	return calculateDist(encoderValue);
}

	task main()
{
string text;
	eraseDisplay();
	float travelled = abs(findIR(IR));
	stopMotors();
	sprintf(text, "left = %i", nMotorEncoder[leftFront]);
	displayCenteredTextLine(4, text);
	sprintf(text, "right = %i", nMotorEncoder[rightFront]);
	displayCenteredTextLine(5, text);
	sprintf(text, "distance = %f", travelled);
	displayCenteredTextLine(1, text);
}
