#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl)
#pragma config(Motor,  mtr_S1_C1_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    goalCapture,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "liftTask.c"
#include "rpgCommon.c"

task main
{
	while(true)
	{
		if(joy1Btn(JOY_BUTTON_A))
		{
			if(otherTask == true)
			{
				stopTask(liftTask);
				otherTask = false;
			}

			FOO(32);
		}

		if(joy1Btn(JOY_BUTTON_B))
		{
			if(otherTask == true)
			{
				stopTask(liftTask);
				otherTask = false;
			}

			FOO(62);
		}

		if(joy1Btn(JOY_BUTTON_X))
		{
			if(otherTask == true)
			{
				stopTask(liftTask);
				otherTask = false;
			}

			FOO(92);
		}

		if(joy1Btn(JOY_BUTTON_Y))
		{
			if(otherTask == true)
			{
				stopTask(liftTask);
				otherTask = false;
			}

			FOO(124);
		}
	}
}
