#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     Touch,          sensorTouch)
#pragma config(Sensor, S4,     gyro,           sensorNone)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LiftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     LiftLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     rightBack,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This is the 4-wheel mecanum pragmas
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     Touch,          sensorTouch)
#pragma config(Sensor, S4,     gyro,           sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LiftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     LiftLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     rightBack,     tmotorTetrix, openLoop)


//This is the 2-wheel pragmas
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl)


//sensors
#pragma config(Sensor, S3,     Touch,          sensorTouch)
#pragma config(Sensor, S4,     gyro,           sensorNone)
