#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     liftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     spinner,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     rightFront,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     rightBack,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    spinnerServo,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    tipperServo,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    goalCapture,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MUX1 		 msensor_S4_1 //Definitions for mux sensors
#define touch 	 msensor_S4_3

#define CENTERGOAL 24000
#define GOAL60 13000
#define GOAL90 21000

#include "IRsensor.c" //IR functions
#include "lego-touch.h" //Touch sensor functions

const tMUXSensor LTOUCH = msensor_S4_3; //Defining touch sensor

#include "fourWheelMovement.c" //Big robot movement functions
#include "servoFunctions.c" //servo functions
#include "liftFunctions.c" //Lift and spinner functions
#include "gyroSensor.c" //gyro functions
#include "MovementCommon.c" //Math or calculation functions
#include "autoProgramQuestions.c" //Question functions


void initializeRobot() //Initialize function (empty)
{
	spinnerRelease();
	goalSave();
	tipCatch();
	return;
}

task main()
{
	setBluetoothOff(); //Turn bluetooth off (no interference)
	disableDiagnosticsDisplay(); //Clear screen
	eraseDisplay();
	int iDelay = questionInt("Delay?", "left = -1 sec", "right = +1 sec", 0, 30);
	//Run questionInt function to ask about a delay before running autonomous
	wait1Msec(500);
	int delayMsec = iDelay * 1000;
	//Convert answer from questionInt to milliseconds
	wait1Msec(500);
	bool answer = questionBool("ramp or ground?", " ramp=right(t)", "ground=left(f)");
	//Run questionBool to ask about starting position (ramp or ground)

	bool useLift = questionBool("Use lift?", "right = true", "left = false");

	initializeRobot(); //Run empty initialize function

	bool running = true; //Set bool "running" to true

	wait1Msec(delayMsec); //Wait however long user said to before starting

	while (running) //While "running" is true, infinite loop
	{
		if (answer == true) //If user said false (ramp) in questionBool
		{
			displayCenteredTextLine(1, "ramp");
			if(useLift == false)
			{
				displayCenteredTextLine(2, "lift disabled");
			}
			else
			{
				displayCenteredTextLine(2, "lift enabled");
			}
			running = false;
		}
		else //If user said true (ground) in questionBool
		{

			displayCenteredTextLine(1, "ground");
			if(useLift == false)
			{
				displayCenteredTextLine(2, "lift disabled");
			}
			else
			{
				displayCenteredTextLine(2, "lift enabled");
			}
			running = false;
		}
	}
	wait1Msec(30000);
}
