#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    spinnerServo,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    goalCapture,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MUX1 		 msensor_S4_1 //Definitions for mux sensors
#define touch 	 msensor_S4_2
#define sonar    msensor_S4_3

#include "IRsensor.c" //IR functions
#include "fourWheelMovement.c" //Big robot-specific functions
#include "gyroSensor.c" //gyro functions
#include "MovementCommon.c" //Math or calculation functions
#include "sonarSensor.c" //Sonar functions
#include "autoKickstand.c" //Strategies and functions for kickstand
#include "autoProgramQuestions.c" //Question functions

void initializeRobot() //Initialize function (empty)
{
	return;
}

task main()
{
	setBluetoothOff(); //Turn bluetooth off (no interference)
	disableDiagnosticsDisplay(); //Clear screen

	int iDelay = questionInt("Delay?", "left = -1 sec", "right = +1 sec", 0, 30);
	//Run questionInt function to ask about a delay before running autonomous
	wait1Msec(500);
	int delayMsec = iDelay * 1000;
	//Convert answer from questionInt to milliseconds
	bool answer = questionBool("ramp or ground?", " ramp=right(t)", "ground=left(f)");
	//Run questionBool to ask about starting position (ramp or ground)

	initializeRobot(); //Run empty initialize function

	waitForStart(); // Wait for the beginning of autonomous phase.

	bool running = true; //Set bool "running" to true

	wait1Msec(delayMsec); //Wait however long user said to before starting

	while (running) //While "running" is true, infinite loop
	{
		if (answer == true) //If user said false (ramp) in questionBool
		{
			autoRamp(); //Run autoRamp function
			running = false; //Set "running" to false (break out of infinite loop)
		}
		else //If user said true (ground) in questionBool
		{
			autoKickstand(); //Run autoKickstand (from ground)
			running = false; //Set "running" to false (break out of infinite loop)
		}
	}
}
