#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          rightFront,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rpgCommon.c"
#include "twoWheelMovement.c"
#include "gyroSensor.c"

task main()
{
	HTGYROstartCal(gyro);
	wait1Msec(100);
	leftTurn(10);
	gyroTurn(90);
	stopMotors();
	wait1Msec(1000);
	HTGYROstartCal(gyro);
	wait1Msec(100);
	rightTurn(10);
	gyroTurn(90);
	stopMotors();
}
