#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          rightFront,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rpgCommon.c"
#include "twoWheelMovement.c"
#include "gyroSensor.c"

task main()
{
	gyroLeftTurn(90, 50);
	stopMotors();
	wait1Msec(1000);
	gyroRightTurn(90, 50);
	stopMotors();
}
