#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "common.h"
#include "twoWheelMovement.c"
#include "hitechnic-sensormux.h"     //Drivers for IR Beacon
//#include "IRsensor.c"
#include "hitechnic-irseeker-v2.h"
#include "IRsensor.c"

/*int getIrReading(tSensors irReceiverPin)
{
  // IRLED 38 kHz for at least 2 ms
  wait1Msec(1);                              // Wait 1 ms
  int ir = SensorValue[irReceiverPin];      // IR receiver -> ir variable
  wait1Msec(1);                              // Down time before recheck
  return ir;
}*/

void faceIR(tSensors ir_seeker)
{
	int	ir_value = getIrReading(IR);
	do
	{
		if(ir_value < 2)
		{
			leftTurn(50);
		}
		else if(ir_value > 2)
		{
			rightTurn(50);
		}
		wait1Msec(1);
		ir_value = getIrReading(IR);
	}
	while(ir_value != 2);
}


task main()
{
//	faceIR(IR);
	stopMotors();
}
