#pragma config(Sensor, S3,     HTIRS2,             sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// this is code for testing anything
#include "twoWheelMovement.c"
#include "MovementCommon.c"

task main()
{
	eraseDisplay();

	travelDistance(10);
}
