#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// this is code for testing anything

#include "JoystickDriver.c"
#include "twoWheelMovement.c"
#include "hitechnic-sensormux.h"     //Drivers for IR Beacon
#include "hitechnic-irseeker-v2.h"
#include "gyroSensor.c"
#include "Common.c"
#include "IRsensor.c"
#include "gyroMovement.c"
#include "MovementCommon.c"
//#include "turnFunction.c"

task main()
{
	eraseDisplay();
	int ir;
	while(true)
	{
		ir = getIRReading(IR);
		string text = sprintf(text, "ir=%i", ir);
		displayCenteredTextLine(1, text);
	}
}
