#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    goalCapture,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*This is a set of movement functions.  Goals: make the robot go forward, backwards, turn,
and go to the side.  */
#include "fourWheelMovement.c"
#include "rpgCommon.c"
#include "MovementCommon.c"

#define deadZone 10

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);  // Update Buttons and Joysticks

		wait1Msec(1);

		if((abs(joystick.joy1_y1) >= deadZone) || (abs(joystick.joy1_y2) >= deadZone))
		{
			setMotion(joystick.joy1_y1, joystick.joy1_y2);
		}
		else if(joystick.joy1_TopHat == 6)
		{
			strafe(50);
		}
		else if(joystick.joy1_TopHat == 2)
		{
			strafe(-50);
		}
		else if(joy1Btn(JOY_BUTTON_A))
		{
			int iCRate = servoChangeRate[goalCapture];	// Save change rate
			servoChangeRate[goalCapture] = 0; 					// Max Speed
			servo[goalCapture] = 10;					// Set servo position
			wait1Msec(20);
			servoChangeRate[goalCapture] = iCRate;			// Reset the servo
		}
		else if(joy1Btn(JOY_BUTTON_B))
		{
			int iCRate = servoChangeRate[goalCapture];	// Save change rate
			servoChangeRate[goalCapture] = 0; 					// Max Speed
			servo[goalCapture] = 255;					// Set servo position
			wait1Msec(20);
			servoChangeRate[goalCapture] = iCRate;			// Reset the servo
		}
		else
		{
			stopMotors();
		}
	}
}
