#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftFront,     tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          rightFront,    tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*This is a set of movement functions.  Goals: make the robot go forward, backwards, turn,
and go to the side.  */
#include "functions\twoWheelMovement.c"

task main()
{
setMotion(127, 127);
wait1Msec(2000);
stopMotors();
wait1Msec(500);
setMotion(-64, -64);
wait1Msec(4000);
strafe(0, 0);
}
