#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(MotorPidSetting,  motorB,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(MotorPidSetting,  motorC,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define nxtorange 3
#define nxtleft 2
#define nxtright 1
#define nxtgrey 0

bool RPGtime = NULL;

string inttostring(int num)
{

}

void back(int time)
{
	motor[motorB] = -100;
	motor[motorC] = -100;
	wait10Msec(time);
}

void forward(int time)
{
	motor[motorB] = 100;
	motor[motorC] = 100;
	wait10Msec(time);
}

bool Question1()
{
	nxtDisplayCenteredTextLine(1, "left = no."); // Displays instructions
	nxtDisplayCenteredTextLine(2, " right = yes."); // Displays instructions
	nxtDisplayCenteredTextLine(4, "go back?");//Displays first question

	while(RPGtime == NULL)
	{
		if(nNxtButtonPressed == nxtright)// checks if the right btn is pushed
		{
			// sets RPGtime to true
			nxtDisplayClearTextLine(4);//clears the question
			RPGtime = true;
			return true;
		}

		if(nNxtButtonPressed == nxtleft)// checks if the left btn is pushed
		{
			// sets RPGtime to false
			nxtDisplayClearTextLine(4);//clears the question
			RPGtime = false;
			return false;
		}
	}
	return true;
}

int Question2()
{
	int answer
	nxtDisplayCenteredTextLine(1, "left = add"); // Displays instructions
	nxtDisplayCenteredTextLine(2, "right = subtract"); // Displays instructions
	nxtDisplayCenteredTextLine(3, "press grey when done"); // Displays instructions
	nxtDisplayCenteredTextLine(5, "taps needed to go");//Displays first question
	nxtDisplayCenteredTextLine(6, answer)

	while(sensorvalue[nxtgrey] = -1)
	{
		if(nNxtButtonpressed == nxtright)// checks if the right btn is pushed
		{
			answer = answer + 1
			nxtDisplayClearTextLine(6)
			nxtDisplayCenteredTextLine(6, answer)
		}

		if(nNxtButtonPressed == 2)// checks if the left btn is pushed
		{
			answer = answer - 1
			nxtDisplayClearTextLine(6)
			nxtDisplayCenteredTextLine(6, answer)
		}

	}

	return answer
}

task main()
{

	bool RPGtime = Question1();//asks the questions
	int taps = question2();
	int tapsdone = 0

	//waitForStart(); //waits for the start of the auto phase
	forward(500);

	if (RPGtime == true)
	{
		back(500);
	}
	else
	{
		forward(500);
	}

	while(taps > tapsdone)
	{
		if(SensorValue[touch] = 1)
		{
			tapsdone = tapsdone+1;
			while(SensorValue[touch] = 1)
			{
				wait1Msec(1)
			}
		}
	}
}
