#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(MotorPidSetting,  motorB,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(MotorPidSetting,  motorC,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define nxtorange 3
#define nxtleft 2
#define nxtright 1
#define nxtgrey 0

bool RPGtime = NULL;

string inttostring(int num)
{

}

void back(int time)
{
	motor[motorB] = -100;
	motor[motorC] = -100;
	wait10Msec(time);
}

void forward(int time)
{
	motor[motorB] = 100;
	motor[motorC] = 100;
	wait10Msec(time);
}

task main()
{

	bool RPGtime = Question1();//asks the questions
	int taps = question2();
	int tapsdone = 0

	//waitForStart(); //waits for the start of the auto phase
	forward(500);

	if (RPGtime == true)
	{
		back(500);
	}
	else
	{
		forward(500);
	}

	while(taps > tapsdone)
	{
		if(SensorValue[touch] = 1)
		{
			tapsdone = tapsdone+1;
			while(SensorValue[touch] = 1)
			{
				wait1Msec(1)
			}
		}
	}
}
