#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     rightBack,      tmotorTetrix, openLoop)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "functions\Common.c"
#include "functions\movement.c"

void initializeRobot()
{
	disableDiagnosticsDisplay();
	eraseDisplay();
  return;
}


void displayStatus()
{
	displayString(1, "Firmware Ver: %d", version);
	displayString(2, "Bluetooth State: %d", nBluetoothState);
	displayString(3, "NXT Battery: %d", nAvgBatteryLevel);
	displayString(4, "Ext Battery: %d", externalBatteryAvg);

}

task main()
{
  initializeRobot();

  while(nNxtButtonPressed != nxtOrange)
  {
  	displayStatus();
  }

  waitTillNoButton();
  eraseDisplay();
	resetEncoders();

	while(nNxtButtonPressed != nxtOrange)
	{
		while(nxtGrey != nNxtButtonPressed)
		{
			displayString(4,"PICK UP AND PRESS GREY BTN");
		}
		while((nMotorEncoder[rightFront] < 1800)||(nMotorEncoder[rightBack] < 1800)||(nMotorEncoder[leftBack] < 1800)||(nMotorEncoder[leftFront]< 1800))
		{
			eraseDisplay();
			setMotors(70,70,70,70);
		}
		stopMotors();

		displayString(1, "should be 1800");
		displayString(3, "rightback encoder: %d", nMotorEncoder[rightFront]);
		displayString(2, "rightfront encoder: %d", nMotorEncoder[rightBack]);
		displayString(4, "leftfront encoder: %d", nMotorEncoder[leftFront]);
		displayString(5, "leftback encoder: %d", nMotorEncoder[leftBack]);
	}

  waitTillNoButton();

}
