#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     sTouch,         sensorTouch)
#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



void initializeRobot()
{
	disableDiagnosticsDisplay();
	eraseDisplay();
  return;
}


void displayStatus()
{
	nxtDisplayString(1, "Firmware Ver: %d", version);
	nxtDisplayString(2, "Bluetooth State: %d", nBluetoothState);
	nxtDisplayString(3, "NXT Battery: %d", nAvgBatteryLevel);
	nxtDisplayString(4, "Ext Battery: %d", externalBatteryAvg);

}

task main()
{
  initializeRobot();

  while (true) {
  	displayStatus();
  }
}
