#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     IR,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     rightBack,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "twoWheelMovement.c"

void faceIR()
{
	int	ir_value = SensorValue[IR];
	if(ir_value < 5)
	{
		do
		{
			setMotion(-64, 64);
			wait1Msec(10);
			ir_value = SensorValue[IR];
		}
		while(ir_value != 5);
	}
	else if(ir_value > 5)
	{
		do
		{
			setMotion(64, -64);
			wait1Msec(10);
			ir_value = SensorValue[IR];
		}
		while(ir_value != 5);
	}
	else
	{
		stopMotors();
	}
}

task main()
{
	faceIR();
}
